// source: ubiquity/serialization/Quantum.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ubiquity_serialization_Field_pb = require('../../ubiquity/serialization/Field_pb.js');
goog.object.extend(proto, ubiquity_serialization_Field_pb);
var ubiquity_serialization_Method_pb = require('../../ubiquity/serialization/Method_pb.js');
goog.object.extend(proto, ubiquity_serialization_Method_pb);
goog.exportSymbol('proto.QuantumPB', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.QuantumPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.QuantumPB.repeatedFields_, null);
};
goog.inherits(proto.QuantumPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.QuantumPB.displayName = 'proto.QuantumPB';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.QuantumPB.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.QuantumPB.prototype.toObject = function(opt_includeInstance) {
  return proto.QuantumPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.QuantumPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QuantumPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    fieldsList: jspb.Message.toObjectList(msg.getFieldsList(),
    ubiquity_serialization_Field_pb.FieldPB.toObject, includeInstance),
    methodsList: jspb.Message.toObjectList(msg.getMethodsList(),
    ubiquity_serialization_Method_pb.MethodPB.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.QuantumPB}
 */
proto.QuantumPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.QuantumPB;
  return proto.QuantumPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.QuantumPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.QuantumPB}
 */
proto.QuantumPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = new ubiquity_serialization_Field_pb.FieldPB;
      reader.readMessage(value,ubiquity_serialization_Field_pb.FieldPB.deserializeBinaryFromReader);
      msg.addFields(value);
      break;
    case 3:
      var value = new ubiquity_serialization_Method_pb.MethodPB;
      reader.readMessage(value,ubiquity_serialization_Method_pb.MethodPB.deserializeBinaryFromReader);
      msg.addMethods(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.QuantumPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.QuantumPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.QuantumPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.QuantumPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      ubiquity_serialization_Field_pb.FieldPB.serializeBinaryToWriter
    );
  }
  f = message.getMethodsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      ubiquity_serialization_Method_pb.MethodPB.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.QuantumPB.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.QuantumPB} returns this
 */
proto.QuantumPB.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated FieldPB fields = 2;
 * @return {!Array<!proto.FieldPB>}
 */
proto.QuantumPB.prototype.getFieldsList = function() {
  return /** @type{!Array<!proto.FieldPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, ubiquity_serialization_Field_pb.FieldPB, 2));
};


/**
 * @param {!Array<!proto.FieldPB>} value
 * @return {!proto.QuantumPB} returns this
*/
proto.QuantumPB.prototype.setFieldsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.FieldPB=} opt_value
 * @param {number=} opt_index
 * @return {!proto.FieldPB}
 */
proto.QuantumPB.prototype.addFields = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.FieldPB, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.QuantumPB} returns this
 */
proto.QuantumPB.prototype.clearFieldsList = function() {
  return this.setFieldsList([]);
};


/**
 * repeated MethodPB methods = 3;
 * @return {!Array<!proto.MethodPB>}
 */
proto.QuantumPB.prototype.getMethodsList = function() {
  return /** @type{!Array<!proto.MethodPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, ubiquity_serialization_Method_pb.MethodPB, 3));
};


/**
 * @param {!Array<!proto.MethodPB>} value
 * @return {!proto.QuantumPB} returns this
*/
proto.QuantumPB.prototype.setMethodsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.MethodPB=} opt_value
 * @param {number=} opt_index
 * @return {!proto.MethodPB}
 */
proto.QuantumPB.prototype.addMethods = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.MethodPB, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.QuantumPB} returns this
 */
proto.QuantumPB.prototype.clearMethodsList = function() {
  return this.setMethodsList([]);
};


goog.object.extend(exports, proto);
