// source: ubiquity/serialization/Wave.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var ubiquity_serialization_Shoebox_pb = require('../../ubiquity/serialization/Shoebox_pb.js');
goog.object.extend(proto, ubiquity_serialization_Shoebox_pb);
var ubiquity_serialization_Field_pb = require('../../ubiquity/serialization/Field_pb.js');
goog.object.extend(proto, ubiquity_serialization_Field_pb);
var ubiquity_serialization_Method_pb = require('../../ubiquity/serialization/Method_pb.js');
goog.object.extend(proto, ubiquity_serialization_Method_pb);
goog.exportSymbol('proto.ErrorPB', null, global);
goog.exportSymbol('proto.FieldGetRequestPB', null, global);
goog.exportSymbol('proto.FieldGetResponsePB', null, global);
goog.exportSymbol('proto.FieldSetRequestPB', null, global);
goog.exportSymbol('proto.FieldSetResponsePB', null, global);
goog.exportSymbol('proto.MethodCallRequestPB', null, global);
goog.exportSymbol('proto.MethodCallResponsePB', null, global);
goog.exportSymbol('proto.WaveHeaderPB', null, global);
goog.exportSymbol('proto.WavePB', null, global);
goog.exportSymbol('proto.WavePB.DataCase', null, global);
goog.exportSymbol('proto.WaveTypePB', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WavePB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.WavePB.oneofGroups_);
};
goog.inherits(proto.WavePB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WavePB.displayName = 'proto.WavePB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WaveHeaderPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WaveHeaderPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WaveHeaderPB.displayName = 'proto.WaveHeaderPB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FieldGetRequestPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FieldGetRequestPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FieldGetRequestPB.displayName = 'proto.FieldGetRequestPB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FieldGetResponsePB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FieldGetResponsePB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FieldGetResponsePB.displayName = 'proto.FieldGetResponsePB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FieldSetRequestPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FieldSetRequestPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FieldSetRequestPB.displayName = 'proto.FieldSetRequestPB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.FieldSetResponsePB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.FieldSetResponsePB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.FieldSetResponsePB.displayName = 'proto.FieldSetResponsePB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MethodCallRequestPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.MethodCallRequestPB.repeatedFields_, null);
};
goog.inherits(proto.MethodCallRequestPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MethodCallRequestPB.displayName = 'proto.MethodCallRequestPB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MethodCallResponsePB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MethodCallResponsePB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.MethodCallResponsePB.displayName = 'proto.MethodCallResponsePB';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ErrorPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ErrorPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ErrorPB.displayName = 'proto.ErrorPB';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.WavePB.oneofGroups_ = [[10,11,12,13,14,15,16,17]];

/**
 * @enum {number}
 */
proto.WavePB.DataCase = {
  DATA_NOT_SET: 0,
  SHOEBOX: 10,
  FIELD_GET_REQUEST: 11,
  FIELD_GET_RESPONSE: 12,
  FIELD_SET_REQUEST: 13,
  FIELD_SET_RESPONSE: 14,
  METHOD_CALL_REQUEST: 15,
  METHOD_CALL_RESPONSE: 16,
  ERROR: 17
};

/**
 * @return {proto.WavePB.DataCase}
 */
proto.WavePB.prototype.getDataCase = function() {
  return /** @type {proto.WavePB.DataCase} */(jspb.Message.computeOneofCase(this, proto.WavePB.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WavePB.prototype.toObject = function(opt_includeInstance) {
  return proto.WavePB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WavePB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WavePB.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.WaveHeaderPB.toObject(includeInstance, f),
    shoebox: (f = msg.getShoebox()) && ubiquity_serialization_Shoebox_pb.ShoeboxPB.toObject(includeInstance, f),
    fieldGetRequest: (f = msg.getFieldGetRequest()) && proto.FieldGetRequestPB.toObject(includeInstance, f),
    fieldGetResponse: (f = msg.getFieldGetResponse()) && proto.FieldGetResponsePB.toObject(includeInstance, f),
    fieldSetRequest: (f = msg.getFieldSetRequest()) && proto.FieldSetRequestPB.toObject(includeInstance, f),
    fieldSetResponse: (f = msg.getFieldSetResponse()) && proto.FieldSetResponsePB.toObject(includeInstance, f),
    methodCallRequest: (f = msg.getMethodCallRequest()) && proto.MethodCallRequestPB.toObject(includeInstance, f),
    methodCallResponse: (f = msg.getMethodCallResponse()) && proto.MethodCallResponsePB.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.ErrorPB.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WavePB}
 */
proto.WavePB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WavePB;
  return proto.WavePB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WavePB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WavePB}
 */
proto.WavePB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.WaveHeaderPB;
      reader.readMessage(value,proto.WaveHeaderPB.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 10:
      var value = new ubiquity_serialization_Shoebox_pb.ShoeboxPB;
      reader.readMessage(value,ubiquity_serialization_Shoebox_pb.ShoeboxPB.deserializeBinaryFromReader);
      msg.setShoebox(value);
      break;
    case 11:
      var value = new proto.FieldGetRequestPB;
      reader.readMessage(value,proto.FieldGetRequestPB.deserializeBinaryFromReader);
      msg.setFieldGetRequest(value);
      break;
    case 12:
      var value = new proto.FieldGetResponsePB;
      reader.readMessage(value,proto.FieldGetResponsePB.deserializeBinaryFromReader);
      msg.setFieldGetResponse(value);
      break;
    case 13:
      var value = new proto.FieldSetRequestPB;
      reader.readMessage(value,proto.FieldSetRequestPB.deserializeBinaryFromReader);
      msg.setFieldSetRequest(value);
      break;
    case 14:
      var value = new proto.FieldSetResponsePB;
      reader.readMessage(value,proto.FieldSetResponsePB.deserializeBinaryFromReader);
      msg.setFieldSetResponse(value);
      break;
    case 15:
      var value = new proto.MethodCallRequestPB;
      reader.readMessage(value,proto.MethodCallRequestPB.deserializeBinaryFromReader);
      msg.setMethodCallRequest(value);
      break;
    case 16:
      var value = new proto.MethodCallResponsePB;
      reader.readMessage(value,proto.MethodCallResponsePB.deserializeBinaryFromReader);
      msg.setMethodCallResponse(value);
      break;
    case 17:
      var value = new proto.ErrorPB;
      reader.readMessage(value,proto.ErrorPB.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WavePB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WavePB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WavePB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WavePB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.WaveHeaderPB.serializeBinaryToWriter
    );
  }
  f = message.getShoebox();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      ubiquity_serialization_Shoebox_pb.ShoeboxPB.serializeBinaryToWriter
    );
  }
  f = message.getFieldGetRequest();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.FieldGetRequestPB.serializeBinaryToWriter
    );
  }
  f = message.getFieldGetResponse();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.FieldGetResponsePB.serializeBinaryToWriter
    );
  }
  f = message.getFieldSetRequest();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.FieldSetRequestPB.serializeBinaryToWriter
    );
  }
  f = message.getFieldSetResponse();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.FieldSetResponsePB.serializeBinaryToWriter
    );
  }
  f = message.getMethodCallRequest();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.MethodCallRequestPB.serializeBinaryToWriter
    );
  }
  f = message.getMethodCallResponse();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.MethodCallResponsePB.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.ErrorPB.serializeBinaryToWriter
    );
  }
};


/**
 * optional WaveHeaderPB header = 1;
 * @return {?proto.WaveHeaderPB}
 */
proto.WavePB.prototype.getHeader = function() {
  return /** @type{?proto.WaveHeaderPB} */ (
    jspb.Message.getWrapperField(this, proto.WaveHeaderPB, 1));
};


/**
 * @param {?proto.WaveHeaderPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ShoeboxPB shoebox = 10;
 * @return {?proto.ShoeboxPB}
 */
proto.WavePB.prototype.getShoebox = function() {
  return /** @type{?proto.ShoeboxPB} */ (
    jspb.Message.getWrapperField(this, ubiquity_serialization_Shoebox_pb.ShoeboxPB, 10));
};


/**
 * @param {?proto.ShoeboxPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setShoebox = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearShoebox = function() {
  return this.setShoebox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasShoebox = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional FieldGetRequestPB field_get_request = 11;
 * @return {?proto.FieldGetRequestPB}
 */
proto.WavePB.prototype.getFieldGetRequest = function() {
  return /** @type{?proto.FieldGetRequestPB} */ (
    jspb.Message.getWrapperField(this, proto.FieldGetRequestPB, 11));
};


/**
 * @param {?proto.FieldGetRequestPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setFieldGetRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearFieldGetRequest = function() {
  return this.setFieldGetRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasFieldGetRequest = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional FieldGetResponsePB field_get_response = 12;
 * @return {?proto.FieldGetResponsePB}
 */
proto.WavePB.prototype.getFieldGetResponse = function() {
  return /** @type{?proto.FieldGetResponsePB} */ (
    jspb.Message.getWrapperField(this, proto.FieldGetResponsePB, 12));
};


/**
 * @param {?proto.FieldGetResponsePB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setFieldGetResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearFieldGetResponse = function() {
  return this.setFieldGetResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasFieldGetResponse = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional FieldSetRequestPB field_set_request = 13;
 * @return {?proto.FieldSetRequestPB}
 */
proto.WavePB.prototype.getFieldSetRequest = function() {
  return /** @type{?proto.FieldSetRequestPB} */ (
    jspb.Message.getWrapperField(this, proto.FieldSetRequestPB, 13));
};


/**
 * @param {?proto.FieldSetRequestPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setFieldSetRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearFieldSetRequest = function() {
  return this.setFieldSetRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasFieldSetRequest = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional FieldSetResponsePB field_set_response = 14;
 * @return {?proto.FieldSetResponsePB}
 */
proto.WavePB.prototype.getFieldSetResponse = function() {
  return /** @type{?proto.FieldSetResponsePB} */ (
    jspb.Message.getWrapperField(this, proto.FieldSetResponsePB, 14));
};


/**
 * @param {?proto.FieldSetResponsePB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setFieldSetResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearFieldSetResponse = function() {
  return this.setFieldSetResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasFieldSetResponse = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional MethodCallRequestPB method_call_request = 15;
 * @return {?proto.MethodCallRequestPB}
 */
proto.WavePB.prototype.getMethodCallRequest = function() {
  return /** @type{?proto.MethodCallRequestPB} */ (
    jspb.Message.getWrapperField(this, proto.MethodCallRequestPB, 15));
};


/**
 * @param {?proto.MethodCallRequestPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setMethodCallRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearMethodCallRequest = function() {
  return this.setMethodCallRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasMethodCallRequest = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional MethodCallResponsePB method_call_response = 16;
 * @return {?proto.MethodCallResponsePB}
 */
proto.WavePB.prototype.getMethodCallResponse = function() {
  return /** @type{?proto.MethodCallResponsePB} */ (
    jspb.Message.getWrapperField(this, proto.MethodCallResponsePB, 16));
};


/**
 * @param {?proto.MethodCallResponsePB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setMethodCallResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 16, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearMethodCallResponse = function() {
  return this.setMethodCallResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasMethodCallResponse = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional ErrorPB error = 17;
 * @return {?proto.ErrorPB}
 */
proto.WavePB.prototype.getError = function() {
  return /** @type{?proto.ErrorPB} */ (
    jspb.Message.getWrapperField(this, proto.ErrorPB, 17));
};


/**
 * @param {?proto.ErrorPB|undefined} value
 * @return {!proto.WavePB} returns this
*/
proto.WavePB.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 17, proto.WavePB.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WavePB} returns this
 */
proto.WavePB.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WavePB.prototype.hasError = function() {
  return jspb.Message.getField(this, 17) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WaveHeaderPB.prototype.toObject = function(opt_includeInstance) {
  return proto.WaveHeaderPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WaveHeaderPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WaveHeaderPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    shoebox: jspb.Message.getFieldWithDefault(msg, 3, ""),
    quantumId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    requestWave: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WaveHeaderPB}
 */
proto.WaveHeaderPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WaveHeaderPB;
  return proto.WaveHeaderPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WaveHeaderPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WaveHeaderPB}
 */
proto.WaveHeaderPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.WaveTypePB} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setShoebox(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setQuantumId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestWave(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WaveHeaderPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WaveHeaderPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WaveHeaderPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WaveHeaderPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getShoebox();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getQuantumId();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getRequestWave();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.WaveHeaderPB.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.WaveHeaderPB} returns this
 */
proto.WaveHeaderPB.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional WaveTypePB type = 2;
 * @return {!proto.WaveTypePB}
 */
proto.WaveHeaderPB.prototype.getType = function() {
  return /** @type {!proto.WaveTypePB} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.WaveTypePB} value
 * @return {!proto.WaveHeaderPB} returns this
 */
proto.WaveHeaderPB.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string shoebox = 3;
 * @return {string}
 */
proto.WaveHeaderPB.prototype.getShoebox = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.WaveHeaderPB} returns this
 */
proto.WaveHeaderPB.prototype.setShoebox = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 quantum_id = 4;
 * @return {number}
 */
proto.WaveHeaderPB.prototype.getQuantumId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.WaveHeaderPB} returns this
 */
proto.WaveHeaderPB.prototype.setQuantumId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string request_wave = 5;
 * @return {string}
 */
proto.WaveHeaderPB.prototype.getRequestWave = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.WaveHeaderPB} returns this
 */
proto.WaveHeaderPB.prototype.setRequestWave = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FieldGetRequestPB.prototype.toObject = function(opt_includeInstance) {
  return proto.FieldGetRequestPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FieldGetRequestPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldGetRequestPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    field: (f = msg.getField()) && ubiquity_serialization_Field_pb.FieldPB.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FieldGetRequestPB}
 */
proto.FieldGetRequestPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FieldGetRequestPB;
  return proto.FieldGetRequestPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FieldGetRequestPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FieldGetRequestPB}
 */
proto.FieldGetRequestPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ubiquity_serialization_Field_pb.FieldPB;
      reader.readMessage(value,ubiquity_serialization_Field_pb.FieldPB.deserializeBinaryFromReader);
      msg.setField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FieldGetRequestPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FieldGetRequestPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FieldGetRequestPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldGetRequestPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ubiquity_serialization_Field_pb.FieldPB.serializeBinaryToWriter
    );
  }
};


/**
 * optional FieldPB field = 1;
 * @return {?proto.FieldPB}
 */
proto.FieldGetRequestPB.prototype.getField = function() {
  return /** @type{?proto.FieldPB} */ (
    jspb.Message.getWrapperField(this, ubiquity_serialization_Field_pb.FieldPB, 1));
};


/**
 * @param {?proto.FieldPB|undefined} value
 * @return {!proto.FieldGetRequestPB} returns this
*/
proto.FieldGetRequestPB.prototype.setField = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.FieldGetRequestPB} returns this
 */
proto.FieldGetRequestPB.prototype.clearField = function() {
  return this.setField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FieldGetRequestPB.prototype.hasField = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FieldGetResponsePB.prototype.toObject = function(opt_includeInstance) {
  return proto.FieldGetResponsePB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FieldGetResponsePB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldGetResponsePB.toObject = function(includeInstance, msg) {
  var f, obj = {
    returnValue: (f = msg.getReturnValue()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FieldGetResponsePB}
 */
proto.FieldGetResponsePB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FieldGetResponsePB;
  return proto.FieldGetResponsePB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FieldGetResponsePB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FieldGetResponsePB}
 */
proto.FieldGetResponsePB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setReturnValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FieldGetResponsePB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FieldGetResponsePB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FieldGetResponsePB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldGetResponsePB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReturnValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Any return_value = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.FieldGetResponsePB.prototype.getReturnValue = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.FieldGetResponsePB} returns this
*/
proto.FieldGetResponsePB.prototype.setReturnValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.FieldGetResponsePB} returns this
 */
proto.FieldGetResponsePB.prototype.clearReturnValue = function() {
  return this.setReturnValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FieldGetResponsePB.prototype.hasReturnValue = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FieldSetRequestPB.prototype.toObject = function(opt_includeInstance) {
  return proto.FieldSetRequestPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FieldSetRequestPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldSetRequestPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    field: (f = msg.getField()) && ubiquity_serialization_Field_pb.FieldPB.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FieldSetRequestPB}
 */
proto.FieldSetRequestPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FieldSetRequestPB;
  return proto.FieldSetRequestPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FieldSetRequestPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FieldSetRequestPB}
 */
proto.FieldSetRequestPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ubiquity_serialization_Field_pb.FieldPB;
      reader.readMessage(value,ubiquity_serialization_Field_pb.FieldPB.deserializeBinaryFromReader);
      msg.setField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FieldSetRequestPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FieldSetRequestPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FieldSetRequestPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldSetRequestPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ubiquity_serialization_Field_pb.FieldPB.serializeBinaryToWriter
    );
  }
};


/**
 * optional FieldPB field = 1;
 * @return {?proto.FieldPB}
 */
proto.FieldSetRequestPB.prototype.getField = function() {
  return /** @type{?proto.FieldPB} */ (
    jspb.Message.getWrapperField(this, ubiquity_serialization_Field_pb.FieldPB, 1));
};


/**
 * @param {?proto.FieldPB|undefined} value
 * @return {!proto.FieldSetRequestPB} returns this
*/
proto.FieldSetRequestPB.prototype.setField = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.FieldSetRequestPB} returns this
 */
proto.FieldSetRequestPB.prototype.clearField = function() {
  return this.setField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.FieldSetRequestPB.prototype.hasField = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.FieldSetResponsePB.prototype.toObject = function(opt_includeInstance) {
  return proto.FieldSetResponsePB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.FieldSetResponsePB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldSetResponsePB.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.FieldSetResponsePB}
 */
proto.FieldSetResponsePB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.FieldSetResponsePB;
  return proto.FieldSetResponsePB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.FieldSetResponsePB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.FieldSetResponsePB}
 */
proto.FieldSetResponsePB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.FieldSetResponsePB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.FieldSetResponsePB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.FieldSetResponsePB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.FieldSetResponsePB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MethodCallRequestPB.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MethodCallRequestPB.prototype.toObject = function(opt_includeInstance) {
  return proto.MethodCallRequestPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MethodCallRequestPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MethodCallRequestPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    method: (f = msg.getMethod()) && ubiquity_serialization_Method_pb.MethodPB.toObject(includeInstance, f),
    argumentsList: jspb.Message.toObjectList(msg.getArgumentsList(),
    ubiquity_serialization_Method_pb.ParameterPB.toObject, includeInstance),
    kwargumentsList: jspb.Message.toObjectList(msg.getKwargumentsList(),
    ubiquity_serialization_Method_pb.ParameterPB.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MethodCallRequestPB}
 */
proto.MethodCallRequestPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MethodCallRequestPB;
  return proto.MethodCallRequestPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MethodCallRequestPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MethodCallRequestPB}
 */
proto.MethodCallRequestPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ubiquity_serialization_Method_pb.MethodPB;
      reader.readMessage(value,ubiquity_serialization_Method_pb.MethodPB.deserializeBinaryFromReader);
      msg.setMethod(value);
      break;
    case 2:
      var value = new ubiquity_serialization_Method_pb.ParameterPB;
      reader.readMessage(value,ubiquity_serialization_Method_pb.ParameterPB.deserializeBinaryFromReader);
      msg.addArguments(value);
      break;
    case 3:
      var value = new ubiquity_serialization_Method_pb.ParameterPB;
      reader.readMessage(value,ubiquity_serialization_Method_pb.ParameterPB.deserializeBinaryFromReader);
      msg.addKwarguments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MethodCallRequestPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MethodCallRequestPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MethodCallRequestPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MethodCallRequestPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMethod();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      ubiquity_serialization_Method_pb.MethodPB.serializeBinaryToWriter
    );
  }
  f = message.getArgumentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      ubiquity_serialization_Method_pb.ParameterPB.serializeBinaryToWriter
    );
  }
  f = message.getKwargumentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      ubiquity_serialization_Method_pb.ParameterPB.serializeBinaryToWriter
    );
  }
};


/**
 * optional MethodPB method = 1;
 * @return {?proto.MethodPB}
 */
proto.MethodCallRequestPB.prototype.getMethod = function() {
  return /** @type{?proto.MethodPB} */ (
    jspb.Message.getWrapperField(this, ubiquity_serialization_Method_pb.MethodPB, 1));
};


/**
 * @param {?proto.MethodPB|undefined} value
 * @return {!proto.MethodCallRequestPB} returns this
*/
proto.MethodCallRequestPB.prototype.setMethod = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MethodCallRequestPB} returns this
 */
proto.MethodCallRequestPB.prototype.clearMethod = function() {
  return this.setMethod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MethodCallRequestPB.prototype.hasMethod = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated ParameterPB arguments = 2;
 * @return {!Array<!proto.ParameterPB>}
 */
proto.MethodCallRequestPB.prototype.getArgumentsList = function() {
  return /** @type{!Array<!proto.ParameterPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, ubiquity_serialization_Method_pb.ParameterPB, 2));
};


/**
 * @param {!Array<!proto.ParameterPB>} value
 * @return {!proto.MethodCallRequestPB} returns this
*/
proto.MethodCallRequestPB.prototype.setArgumentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ParameterPB=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ParameterPB}
 */
proto.MethodCallRequestPB.prototype.addArguments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ParameterPB, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MethodCallRequestPB} returns this
 */
proto.MethodCallRequestPB.prototype.clearArgumentsList = function() {
  return this.setArgumentsList([]);
};


/**
 * repeated ParameterPB kwarguments = 3;
 * @return {!Array<!proto.ParameterPB>}
 */
proto.MethodCallRequestPB.prototype.getKwargumentsList = function() {
  return /** @type{!Array<!proto.ParameterPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, ubiquity_serialization_Method_pb.ParameterPB, 3));
};


/**
 * @param {!Array<!proto.ParameterPB>} value
 * @return {!proto.MethodCallRequestPB} returns this
*/
proto.MethodCallRequestPB.prototype.setKwargumentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.ParameterPB=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ParameterPB}
 */
proto.MethodCallRequestPB.prototype.addKwarguments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.ParameterPB, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MethodCallRequestPB} returns this
 */
proto.MethodCallRequestPB.prototype.clearKwargumentsList = function() {
  return this.setKwargumentsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MethodCallResponsePB.prototype.toObject = function(opt_includeInstance) {
  return proto.MethodCallResponsePB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MethodCallResponsePB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MethodCallResponsePB.toObject = function(includeInstance, msg) {
  var f, obj = {
    returnValue: (f = msg.getReturnValue()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MethodCallResponsePB}
 */
proto.MethodCallResponsePB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MethodCallResponsePB;
  return proto.MethodCallResponsePB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MethodCallResponsePB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MethodCallResponsePB}
 */
proto.MethodCallResponsePB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setReturnValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MethodCallResponsePB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MethodCallResponsePB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MethodCallResponsePB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MethodCallResponsePB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReturnValue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Any return_value = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.MethodCallResponsePB.prototype.getReturnValue = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.MethodCallResponsePB} returns this
*/
proto.MethodCallResponsePB.prototype.setReturnValue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.MethodCallResponsePB} returns this
 */
proto.MethodCallResponsePB.prototype.clearReturnValue = function() {
  return this.setReturnValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.MethodCallResponsePB.prototype.hasReturnValue = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ErrorPB.prototype.toObject = function(opt_includeInstance) {
  return proto.ErrorPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ErrorPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ErrorPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ErrorPB}
 */
proto.ErrorPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ErrorPB;
  return proto.ErrorPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ErrorPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ErrorPB}
 */
proto.ErrorPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ErrorPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ErrorPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ErrorPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ErrorPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string error = 1;
 * @return {string}
 */
proto.ErrorPB.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ErrorPB} returns this
 */
proto.ErrorPB.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.WaveTypePB = {
  NONE: 0,
  SHOEBOX: 1,
  FIELD_GETTER_REQUEST: 2,
  FIELD_GETTER_RESPONSE: 3,
  FIELD_SETTER_REQUEST: 4,
  FIELD_SETTER_RESPONSE: 5,
  METHOD_CALL_REQUEST: 6,
  METHOD_CALL_RESPONSE: 7,
  ERROR: 20
};

goog.object.extend(exports, proto);
