# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubiquity/serialization/Header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ubiquity/serialization/Header.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#ubiquity/serialization/Header.proto\"I\n\x08HeaderPB\x12\x14\n\x0crequest_wave\x18\x01 \x01(\t\x12\x14\n\x0cshoebox_name\x18\x02 \x01(\t\x12\x11\n\tobject_id\x18\x03 \x01(\x03\x62\x06proto3')
)




_HEADERPB = _descriptor.Descriptor(
  name='HeaderPB',
  full_name='HeaderPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_wave', full_name='HeaderPB.request_wave', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shoebox_name', full_name='HeaderPB.shoebox_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='HeaderPB.object_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['HeaderPB'] = _HEADERPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeaderPB = _reflection.GeneratedProtocolMessageType('HeaderPB', (_message.Message,), {
  'DESCRIPTOR' : _HEADERPB,
  '__module__' : 'ubiquity.serialization.Header_pb2'
  # @@protoc_insertion_point(class_scope:HeaderPB)
  })
_sym_db.RegisterMessage(HeaderPB)


# @@protoc_insertion_point(module_scope)
