# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubiquity/serialization/Method.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ubiquity/serialization/Method.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#ubiquity/serialization/Method.proto\x1a\x19google/protobuf/any.proto\"4\n\x08MethodPB\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x0c.ParameterPB\"\xa1\x01\n\x0bParameterPB\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x04type\x18\x02 \x01(\x0e\x32\x10.ParameterTypePB\x12\x12\n\nannotation\x18\x03 \x01(\t\x12+\n\rdefault_value\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12#\n\x05value\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any*`\n\x0fParameterTypePB\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0e\n\nPOSITIONAL\x10\x02\x12\x0b\n\x07KEYWORD\x10\x03\x12\x12\n\x0eVAR_POSITIONAL\x10\x04\x12\x0f\n\x0bVAR_KEYWORD\x10\x05\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_PARAMETERTYPEPB = _descriptor.EnumDescriptor(
  name='ParameterTypePB',
  full_name='ParameterTypePB',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITIONAL', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYWORD', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAR_POSITIONAL', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VAR_KEYWORD', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=284,
  serialized_end=380,
)
_sym_db.RegisterEnumDescriptor(_PARAMETERTYPEPB)

ParameterTypePB = enum_type_wrapper.EnumTypeWrapper(_PARAMETERTYPEPB)
DEFAULT = 0
POSITIONAL = 2
KEYWORD = 3
VAR_POSITIONAL = 4
VAR_KEYWORD = 5



_METHODPB = _descriptor.Descriptor(
  name='MethodPB',
  full_name='MethodPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MethodPB.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='MethodPB.args', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=118,
)


_PARAMETERPB = _descriptor.Descriptor(
  name='ParameterPB',
  full_name='ParameterPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ParameterPB.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ParameterPB.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='ParameterPB.annotation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_value', full_name='ParameterPB.default_value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ParameterPB.value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=282,
)

_METHODPB.fields_by_name['args'].message_type = _PARAMETERPB
_PARAMETERPB.fields_by_name['type'].enum_type = _PARAMETERTYPEPB
_PARAMETERPB.fields_by_name['default_value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_PARAMETERPB.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['MethodPB'] = _METHODPB
DESCRIPTOR.message_types_by_name['ParameterPB'] = _PARAMETERPB
DESCRIPTOR.enum_types_by_name['ParameterTypePB'] = _PARAMETERTYPEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MethodPB = _reflection.GeneratedProtocolMessageType('MethodPB', (_message.Message,), {
  'DESCRIPTOR' : _METHODPB,
  '__module__' : 'ubiquity.serialization.Method_pb2'
  # @@protoc_insertion_point(class_scope:MethodPB)
  })
_sym_db.RegisterMessage(MethodPB)

ParameterPB = _reflection.GeneratedProtocolMessageType('ParameterPB', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERPB,
  '__module__' : 'ubiquity.serialization.Method_pb2'
  # @@protoc_insertion_point(class_scope:ParameterPB)
  })
_sym_db.RegisterMessage(ParameterPB)


# @@protoc_insertion_point(module_scope)
