# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubiquity/serialization/Method.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ubiquity/serialization/Method.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#ubiquity/serialization/Method.proto\x1a\x19google/protobuf/any.proto\"H\n\x08MethodPB\x12\x14\n\x0cshoebox_name\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\x03\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\"E\n\x10MethodArgumentPB\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_METHODPB = _descriptor.Descriptor(
  name='MethodPB',
  full_name='MethodPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shoebox_name', full_name='MethodPB.shoebox_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_id', full_name='MethodPB.object_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='MethodPB.method_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=138,
)


_METHODARGUMENTPB = _descriptor.Descriptor(
  name='MethodArgumentPB',
  full_name='MethodArgumentPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MethodArgumentPB.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='MethodArgumentPB.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=209,
)

_METHODARGUMENTPB.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['MethodPB'] = _METHODPB
DESCRIPTOR.message_types_by_name['MethodArgumentPB'] = _METHODARGUMENTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MethodPB = _reflection.GeneratedProtocolMessageType('MethodPB', (_message.Message,), {
  'DESCRIPTOR' : _METHODPB,
  '__module__' : 'ubiquity.serialization.Method_pb2'
  # @@protoc_insertion_point(class_scope:MethodPB)
  })
_sym_db.RegisterMessage(MethodPB)

MethodArgumentPB = _reflection.GeneratedProtocolMessageType('MethodArgumentPB', (_message.Message,), {
  'DESCRIPTOR' : _METHODARGUMENTPB,
  '__module__' : 'ubiquity.serialization.Method_pb2'
  # @@protoc_insertion_point(class_scope:MethodArgumentPB)
  })
_sym_db.RegisterMessage(MethodArgumentPB)


# @@protoc_insertion_point(module_scope)
