# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubiquity/serialization/Shoebox.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ubiquity/serialization/Shoebox.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$ubiquity/serialization/Shoebox.proto\"5\n\tShoeboxPB\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x06quanta\x18\x02 \x03(\x0b\x32\n.QuantumPB\"\x0b\n\tQuantumPBb\x06proto3')
)




_SHOEBOXPB = _descriptor.Descriptor(
  name='ShoeboxPB',
  full_name='ShoeboxPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ShoeboxPB.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quanta', full_name='ShoeboxPB.quanta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=93,
)


_QUANTUMPB = _descriptor.Descriptor(
  name='QuantumPB',
  full_name='QuantumPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=106,
)

_SHOEBOXPB.fields_by_name['quanta'].message_type = _QUANTUMPB
DESCRIPTOR.message_types_by_name['ShoeboxPB'] = _SHOEBOXPB
DESCRIPTOR.message_types_by_name['QuantumPB'] = _QUANTUMPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShoeboxPB = _reflection.GeneratedProtocolMessageType('ShoeboxPB', (_message.Message,), {
  'DESCRIPTOR' : _SHOEBOXPB,
  '__module__' : 'ubiquity.serialization.Shoebox_pb2'
  # @@protoc_insertion_point(class_scope:ShoeboxPB)
  })
_sym_db.RegisterMessage(ShoeboxPB)

QuantumPB = _reflection.GeneratedProtocolMessageType('QuantumPB', (_message.Message,), {
  'DESCRIPTOR' : _QUANTUMPB,
  '__module__' : 'ubiquity.serialization.Shoebox_pb2'
  # @@protoc_insertion_point(class_scope:QuantumPB)
  })
_sym_db.RegisterMessage(QuantumPB)


# @@protoc_insertion_point(module_scope)
