# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ubiquity/serialization/Shoebox.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ubiquity.serialization import Quantum_pb2 as ubiquity_dot_serialization_dot_Quantum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ubiquity/serialization/Shoebox.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$ubiquity/serialization/Shoebox.proto\x1a$ubiquity/serialization/Quantum.proto\"\x8f\x01\n\tShoeboxPB\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x06quanta\x18\x02 \x03(\x0b\x32\n.QuantumPB\x12(\n\x07objects\x18\x03 \x03(\x0b\x32\x17.ShoeboxPB.ObjectsEntry\x1a.\n\x0cObjectsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[ubiquity_dot_serialization_dot_Quantum__pb2.DESCRIPTOR,])




_SHOEBOXPB_OBJECTSENTRY = _descriptor.Descriptor(
  name='ObjectsEntry',
  full_name='ShoeboxPB.ObjectsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ShoeboxPB.ObjectsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ShoeboxPB.ObjectsEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=222,
)

_SHOEBOXPB = _descriptor.Descriptor(
  name='ShoeboxPB',
  full_name='ShoeboxPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ShoeboxPB.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quanta', full_name='ShoeboxPB.quanta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='ShoeboxPB.objects', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SHOEBOXPB_OBJECTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=222,
)

_SHOEBOXPB_OBJECTSENTRY.containing_type = _SHOEBOXPB
_SHOEBOXPB.fields_by_name['quanta'].message_type = ubiquity_dot_serialization_dot_Quantum__pb2._QUANTUMPB
_SHOEBOXPB.fields_by_name['objects'].message_type = _SHOEBOXPB_OBJECTSENTRY
DESCRIPTOR.message_types_by_name['ShoeboxPB'] = _SHOEBOXPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShoeboxPB = _reflection.GeneratedProtocolMessageType('ShoeboxPB', (_message.Message,), {

  'ObjectsEntry' : _reflection.GeneratedProtocolMessageType('ObjectsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SHOEBOXPB_OBJECTSENTRY,
    '__module__' : 'ubiquity.serialization.Shoebox_pb2'
    # @@protoc_insertion_point(class_scope:ShoeboxPB.ObjectsEntry)
    })
  ,
  'DESCRIPTOR' : _SHOEBOXPB,
  '__module__' : 'ubiquity.serialization.Shoebox_pb2'
  # @@protoc_insertion_point(class_scope:ShoeboxPB)
  })
_sym_db.RegisterMessage(ShoeboxPB)
_sym_db.RegisterMessage(ShoeboxPB.ObjectsEntry)


_SHOEBOXPB_OBJECTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
