// Generated by CoffeeScript 2.5.1
(function() {
  //websocket = require('./websocket')
  var field_pb, protobuf;

  protobuf = require("../serialization/google-protobuf");

  field_pb = require('../serialization/Field_pb');

  //ws = new websocket.WebSocketClientTunnel('localhost')

  //send = () ->
  //  ws.wave_out('ASD')

  //setTimeout(send, 1000)
  console.log(field_pb);

}).call(this);
