// Generated by CoffeeScript 1.12.7
(function() {
  var field_pb, protobuf;

  protobuf = require("../serialization/google-protobuf");

  field_pb = require('../serialization/Field_pb');

  console.log('ASD');

  console.log(field_pb);

}).call(this);
