// Generated by CoffeeScript 2.5.1
(function() {
  String.prototype.format = function(...args) {
    return this.replace(/{(\d+)}/g, function(match, number) {
      if (number < args.length) {
        return args[number];
      } else {
        return match;
      }
    });
  };

}).call(this);
