// source: ubiquity/serialization/Shoebox.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ubiquity_serialization_Quantum_pb = require('../../ubiquity/serialization/Quantum_pb.js');
goog.object.extend(proto, ubiquity_serialization_Quantum_pb);
goog.exportSymbol('proto.ShoeboxPB', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ShoeboxPB = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ShoeboxPB.repeatedFields_, null);
};
goog.inherits(proto.ShoeboxPB, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ShoeboxPB.displayName = 'proto.ShoeboxPB';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ShoeboxPB.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ShoeboxPB.prototype.toObject = function(opt_includeInstance) {
  return proto.ShoeboxPB.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ShoeboxPB} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ShoeboxPB.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    quantaList: jspb.Message.toObjectList(msg.getQuantaList(),
    ubiquity_serialization_Quantum_pb.QuantumPB.toObject, includeInstance),
    objectsMap: (f = msg.getObjectsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ShoeboxPB}
 */
proto.ShoeboxPB.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ShoeboxPB;
  return proto.ShoeboxPB.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ShoeboxPB} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ShoeboxPB}
 */
proto.ShoeboxPB.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new ubiquity_serialization_Quantum_pb.QuantumPB;
      reader.readMessage(value,ubiquity_serialization_Quantum_pb.QuantumPB.deserializeBinaryFromReader);
      msg.addQuanta(value);
      break;
    case 3:
      var value = msg.getObjectsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readInt64, null, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ShoeboxPB.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ShoeboxPB.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ShoeboxPB} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ShoeboxPB.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getQuantaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      ubiquity_serialization_Quantum_pb.QuantumPB.serializeBinaryToWriter
    );
  }
  f = message.getObjectsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeInt64);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.ShoeboxPB.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ShoeboxPB.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated QuantumPB quanta = 2;
 * @return {!Array<!proto.QuantumPB>}
 */
proto.ShoeboxPB.prototype.getQuantaList = function() {
  return /** @type{!Array<!proto.QuantumPB>} */ (
    jspb.Message.getRepeatedWrapperField(this, ubiquity_serialization_Quantum_pb.QuantumPB, 2));
};


/** @param {!Array<!proto.QuantumPB>} value */
proto.ShoeboxPB.prototype.setQuantaList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.QuantumPB=} opt_value
 * @param {number=} opt_index
 * @return {!proto.QuantumPB}
 */
proto.ShoeboxPB.prototype.addQuanta = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.QuantumPB, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.ShoeboxPB.prototype.clearQuantaList = function() {
  this.setQuantaList([]);
};


/**
 * map<string, int64> objects = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.ShoeboxPB.prototype.getObjectsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.ShoeboxPB.prototype.clearObjectsMap = function() {
  this.getObjectsMap().clear();
};


goog.object.extend(exports, proto);
